//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bestMeAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceDetail
    {
        public int code { get; set; }
        public int invoiceNo { get; set; }
        public int Sr_No { get; set; }
        public string comodity { get; set; }
        public string containerNo { get; set; }
        public decimal quantity { get; set; }
        public decimal weight_Ton { get; set; }
        public decimal rate_Ton___ { get; set; }
        public decimal amount___ { get; set; }
    
        public virtual invoiceMaster invoiceMaster { get; set; }
    }
}
